### ISSUE TITLE
資料庫全關

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/dlll-paas-starter#24]
]
=============================
============================
Failed to apply
============================
/app/docker-paas-gitlab-deploy/scripts/ArgocdHelpers.js:532
                    if (values.database.enabled_drivers.indexOf(o.suffix) === -1) {
                                                        ^
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at /app/docker-paas-gitlab-deploy/scripts/ArgocdHelpers.js:532:57
    at Array.filter (<anonymous>)
    at Object.waitForImageSynced (/app/docker-paas-gitlab-deploy/scripts/ArgocdHelpers.js:524:18)
    at processTicksAndRejections (node:internal/process/task_q

https://gitlab.nccu.syntixi.dev/pudding/pudding-demo-0608/-/jobs/10797

**Comment by pulipulichen** [comment]
完成
